name: release
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - run: npm install
      - run: npm run build
      - run: |
          npm install -g json && json -I -f package.json -e '
            this.version = "${{ github.ref }}".replace("refs/tags/", "");
            this.exports = "./dist/src/index.js";
            this.types = "dist/src/index.d.ts";
          '
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
